name: everest
base: core22
version: '0.1'
summary: The Open Source Car Charging Station software
description: |
  EVerest is an open source modular framework for setting up a full stack
  environment for EV charging.

  The modular software architecture fosters customizability and lets you
  configure your dedicated charging scenarios based on interchangeable
  modules. All this is glued together by MQTT.

  EVerest will help to speed the adoption to e-mobility by utilizing all
  the open source advantages for the EV charging world. It will also
  enable new features for local energy management, PV-integration and
  many more.

  The EVerest project was initiated by PIONIX GmbH (Pionix at LinkedIn)
  to help with the electrification of the mobility sector and is an
  official project of the Linux Foundation Energy.

grade: stable
confinement: strict

parts:
  nodered:
    plugin: npm
    source: node-red
    npm-include-node: true
    npm-node-version: 22.1.0
    override-build: |
      craftctl default
      npm install
  edm:
    plugin: python
    source: https://github.com/EVerest/everest-dev-environment.git
    source-subdir: dependency_manager
    after: [ nodered ]
    # do not ship pycache in the snap, instead we'll point 
    # PYTHONPYCACHEPREFIX to $SNAP_COMMON at runtime later to generate
    # the files on first start
    build-environment:
      - PYTHONPYCACHEPREFIX: /tmp/pycache
    override-stage: |
      # clean up duplicated files that will clash with ev-cli below
      for record in pip setuptools MarkupSafe PyYAML jinja2 wheel; do
        rm $CRAFT_PART_INSTALL/lib/python*/*/${record}*/RECORD
      done
      rm $CRAFT_PART_INSTALL/bin/activate* $CRAFT_PART_INSTALL/pyvenv.cfg
      craftctl default
  ev-cli:
    plugin: python
    source: https://github.com/EVerest/everest-utils.git
    source-subdir: ev-dev-tools
    after: [ edm ]
    build-environment:
      - PYTHONPYCACHEPREFIX: /tmp/pycache
  everest:
    plugin: cmake
    source: https://github.com/EVerest/everest-core.git
    after: [ nodered, edm, ev-cli ]
    build-environment:
      - CPM_SOURCE_CACHE: $CRAFT_STAGE/.cache/CPM
      - PATH: $PATH:$CRAFT_STAGE/.local/bin
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_INSTALL_SYSCONFDIR=/etc
    build-packages:
      - rsync
      - wget
      - doxygen
      - graphviz
      - build-essential
      - clang-tidy
      - cppcheck
      - openjdk-17-jdk
      - libboost-all-dev
      - libssl-dev
      - libsqlite3-dev
      - clang-format
      - curl
      - rfkill
      - libpcap-dev
      - libevent-dev
      - pkg-config
      - libcap-dev
    stage-packages:
      - libboost-filesystem1.74.0
      - libboost-log1.74.0
      - libboost-program-options1.74.0
      - libboost-regex1.74.0
      - libboost-thread1.74.0
      - libevent-2.1-7
      - libevent-core-2.1-7
      - libevent-pthreads-2.1-7
      - libicu70
      - libpcap0.8
    prime:
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libicuio.so.70.1
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libicutest.so.70.1
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libicutu.so.70.1
      - -share
      - -usr/share/lintian
      - -usr/share/man
